//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradasVenta
    {
        public int IdVenta { get; set; }
        public int IdEntrada { get; set; }
        public int CantidadEntrada { get; set; }
        public decimal PrecioParcial { get; set; }
    
        public virtual Entrada Entrada { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
